// components/DeviceSelector.vue
<template>
  <div>
    <label for="device-dropdown">Select Device:</label>
    <select id="device-dropdown" :value="selectedDevice || 0"
      @change="(e: Event) => handleSelect(Number((e.target as HTMLSelectElement).value))">
      <option v-for="device in devices" :key="device.index" :value="device.index">
        {{ device.description ? `${device.description} (${device.name})` : device.name }}
      </option>
    </select>
  </div>
</template>

<script lang="ts" setup>
  import type { DeviceInfo } from '~/types/types';
  import { invoke } from '@tauri-apps/api/core';

  const devices = ref<DeviceInfo[]>([]);
  const selectedDevice = ref<number>(0);

  const res = await invoke<DeviceInfo[]>(TAURI_COMMANDS.list_devices);
  devices.value = res;

  async function handleSelect(index: number) {
    try {
      console.debug("set_device", index);
      selectedDevice.value = index;
      await invoke("set_device", { index });
    } catch (error) {
      console.error("Failed to set device:", error);
    }
  }
</script>

<style></style>

// src/components/DeviceSelector.tsx
import { useEffect, useState } from "react";
import { invoke } from '@tauri-apps/api/core';
import { DeviceInfo } from "../types";

function DeviceSelector() {
  const [devices, setDevices] = useState<DeviceInfo[]>([]);
  const [selectedDevice, setSelectedDevice] = useState<number>(0);

  useEffect(() => {
    async function fetchDevices() {
      try {
        const devicesList: DeviceInfo[] = await invoke("list_devices");
        setDevices(devicesList);
      } catch (error) {
        console.error("Failed to fetch devices:", error);
      }
    }

    fetchDevices();
  }, []);

  const handleSelect = async (index: number) => {
    setSelectedDevice(index);
    try {
        console.debug("set_device", index);
      await invoke("set_device", { index });
    } catch (error) {
      console.error("Failed to set device:", error);
    }
  };

  return (
    <div>
      <label htmlFor="device-dropdown">Select Device:</label>
      <select
        id="device-dropdown"
        value={selectedDevice || ""}
        onChange={(e) => handleSelect(Number(e.target.value))}
      >
        {devices.map((device) => (
          <option key={device.index} value={device.index}>
            {
                device.description ? `${device.description} (${device.name})` : device.name
            }   
          </option>
        ))}
      </select>
    </div>
  );
}

export default DeviceSelector;
